### ISSUE TITLE
[BUG] Demo site not changing the language, due 404 on english.json

### ISSUE THREAD

**Issue by JorgeMadson** [thealphadollar/vanilla-i18n#11]
**What happened**: Demo is not changing the content

**What you expected to happen**: Change the language with the select.

**How to reproduce it (as minimally and precisely as possible)**: Go to the demo page and change the language.

**Anything else we need to know?**:

**Environment**:

- version:
- Operating System:
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by thealphadollar** [comment]
Hey Jorge, thanks for bringing the bug to my notice. I've fixed the same via 9dac41f2f1afe08fb8c0b5f16490ad08499dbb21
