### ISSUE TITLE
Add Issues And Pull Request Templates

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/vanilla-i18n#6]
We want to have an issue and a PR template for the project. Here are two resources to start:

- Information about templates: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates
- Some templates that can be used: https://github.com/devspace/awesome-github-templates

**Comment by denisvieiradev** [comment]
@thealphadollar  can assign to me ?

**Comment by thealphadollar** [comment]
Hey Denis, thank you for interest and proactiveness in contributing to the project. I've assigned it to you :100:
