### ISSUE TITLE
[FEAT] allow JSON generation from google sheet link / ID

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/vanilla-i18n#9]
**What would you like to be added**:

Currently, we require the developer to download CSV of translations and thereafter generate language JSONs. However, we can also implement a method where the user can pass in google sheet link / ID in place of the path to CSV and we would generate the language JSONs.

**Why is this needed**:

Eliminates a manual step and saves time.

---

A good place to start for the issue is in the `csv_to_vanilla-i18n` folder and look through the present scripts.

**Comment by RandallWert** [comment]
The approach shown [here](https://learndataanalysis.org/import-google-sheets-to-pandas-dataframe-without-using-google-sheets-api/) would seem to take the data from a Google worksheet to a csv and then to a pandas dataframe in only a few lines of code. Would this approach be acceptable to you?

**Comment by thealphadollar** [comment]
Hey Randall, the method seems like a good start. I'm a bit skeptical as the post was released in 2019. We can surely try and see if we can reach to a useful end.

**Comment by RandallWert** [comment]
Thanks for your reply!

Taking another look at the site that I linked to, it looks like we don't have to deal with pandas at all, because the link to the Google sheet produces a csv as its output. So:

- I could use something like explained [here](https://stackoverflow.com/questions/16283799/how-to-read-a-csv-file-from-a-url-with-python) to use the URL to download the csv.
- That csv content would be input to csv.DictReader().
- And the rest of the code can be left untouched.

Am I understanding that correctly?

**Comment by thealphadollar** [comment]
Yes. I think that should work well. 

So, one way to do this would be allowing a user to pass parameters - `sheetId` and `worksheet` OR `filepath`. According to the input, we can choose to either read the CSV from the filesystem or have it imported from the sheet. The process afterward remains the same. Maybe an intermediate function to do the above at [L35](https://github.com/thealphadollar/vanilla-i18n/blob/8c1d4072022948094939cc6b92f60e5d6cfa0b0c/csv_to_vanilla-i18n/csv_to_vanilla_i18.py#L35) would be cool.

Thanks a lot for doing the research and helping me with the issue :smile: I've assigned the issue to you for now.

**Comment by RandallWert** [comment]
No problem, and thanks for letting me try it :-) I will tackle it later today, when I'm up again.

**Comment by RandallWert** [comment]
I see the sample.csv file, but can you also provide a sample Google sheet for me to test with? It looks like I would need the URL to the sheet, including the sheetId and worksheet name, as you mention.

**Comment by thealphadollar** [comment]
Hey. I guess there's a sheet link in the readme.

**Comment by RandallWert** [comment]
OK, got it. Sorry I missed that.

**Comment by RandallWert** [comment]
OK, I wrote a new version of the original .py file, with both capabilities (local csv or Google sheet via URL). I tested against your sample csv and sample Google sheet. I just went through the whole git workflow and created a pull request.

I am still pretty new to GItHub, so I hope I did things right.
